hf_token: "your_huggingface_token_here"
model_size: "large-v3"

base_path_candidates:
  - "~/OneDrive/Рабочий стол"
  - "~/OneDrive/Desktop"
  - "~/Desktop"

audio_folder_name: "audio"
transcription_folder_name: "transcription"
processing_mode: "single" # single | all
audio_extensions: # supported input formats
  - ".mp3"
  - ".wav"
  - ".m4a"
  - ".flac"
  - ".ogg"
  - ".aac"
  - ".mp4"
  - ".wma"

beam_size: 5
language: null # e.g. "en", "ru" or null for auto-detect
condition_on_previous_text: true
word_timestamps: false

use_batched_inference: false
batch_size: 16

device: "cpu"
compute_type: "int8"
heartbeat_interval_s: 5
